services:
  nammongodb:
    image: mongo:latest
    container_name: nammongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  product-api:
    build: .
    container_name: product-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@nammongodb:27017/product_db?authSource=admin
    depends_on:
      - nammongodb