services:
  nammongodb:
    image: mongo:latest
    container_name: nammongodb_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongod", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  product-api:
    image: unc05/product-api:latest
    container_name: product-api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@nammongodb:27017/product_db?authSource=admin
    depends_on:
      nammongodb:
        condition: service_healthy